image: registry.gitlab.com/moneyappgroup/deployment:latest

variables:
  # Define the user for deployment
  DEPLOY_USER: deploy

before_script:
  # ssh setup
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  # aws setup
  - echo "$AWS_CREDENTIALS" > ~/.aws/credentials
  # Install and run Composer
  - ssh-keyscan -t rsa git.twogether.io >> ~/.ssh/known_hosts
  - php /usr/bin/composer config --global http-basic.composer.biteda.com $COMPOSER_USERNAME $COMPOSER_PASSWORD
  - php /usr/bin/composer install --no-cache --optimize-autoloader
  - echo "PubkeyAcceptedKeyTypes +ssh-rsa" >> $HOME/.ssh/config
  - echo "Host *.dell.aws" >> $HOME/.ssh/config
  - echo "ProxyCommand ssh deploy@bstna.dlpd.net -W %h:%p" >> $HOME/.ssh/config
  - ssh-add -l
  - ssh-keyscan  -t ed25519 bstna.dlpd.net >> ~/.ssh/known_hosts
  - ssh -t deploy@bstna.dlpd.net "ssh-keyscan -t rsa stage.dell.aws" >> ~/.ssh/known_hosts
# Run our tests
#php-test:
#  stage: test
#  script:
#    - ./vendor/bin/phpunit

deploy to stage:
  stage: deploy
  script:
    - cap stage deploy
  environment:
    name: Stage
    url: https://global-list-manager-stage.dellpartnerdirect.net
  only:
    refs:
      - merge_requests
      - tags
      - branches
  when: manual
stages:
  #  - test
  - deploy
