image: $CI_REGISTRY/moneyapp3/moneyapp:latest

variables:
  # Define the user for deployment
  DEPLOY_USER: deploy

before_script:
  # SSH setup
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  # Add GitLab to known hosts
  - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  # AWS setup
  - echo "$AWS_CREDENTIALS" > ~/.aws/credentials
  - chmod 600 ~/.aws/credentials
  # Composer setup (if required)
  - php /usr/bin/composer install --no-cache --optimize-autoloader

# Run our tests (optional)
#php-test:
#  stage: test
#  script:
#    - ./vendor/bin/phpunit

deploy to stage:
  stage: deploy
  script:
    - cap stage deploy
  environment:
    name: Stage
    url: https://global-list-manager-stage.dellpartnerdirect.net
  only:
    refs:
      - merge_requests
      - tags
      - branches
  when: manual

stages:
  # - test
  - deploy
