<?php

namespace Tests\Feature;

use App\Models\Domain;
use App\Models\User;
use Laravel\Passport\Passport;
use PHPUnit\Framework\Attributes\Test;
use Tests\TestCase;

class IndexControllerTest extends TestCase
{

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $user = User::factory()->create();
        Passport::actingAs($user);

        $domain = Domain::factory()->create();

    }

    #[Test]
    public function it_successfully_output_home_content():void
    {
       $this->get(route('home'))
       ->assertOk();
    }

}
